SELECT *FROM AIRLINE;
SELECT COUNT(*) AS COUNT FROM AIRLINE WHERE GENDER='Female';
SELECT COUNT(*) AS TOTAL FROM AIRLINE WHERE CLASS='Business';
SELECT COUNT(*) AS COUNT FROM AIRLINE WHERE CLASS='Eco';
SELECT COUNT(*) AS COUNT FROM AIRLINE WHERE AGE<13;
SELECT COUNT(*) AS COUNT FROM AIRLINE WHERE AGE>16 AND CLASS='Business';